# Site settings
title: What to Do
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Cenas para escrever aqui. Bla bla bla
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost" # the base hostname & protocol for your site
twitter_username: whattodo
github_username:  whattodo

# Build settings
markdown: kramdown

paginate: 4

author: Joao Falcao

gems: [jekyll-paginate]
